
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SidebarPageView from './view/Sidebar/page'
import NavbarPage from './header/navbar/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parkah | FrontEnd Developer',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><link rel="icon" href="/profile/profile2.png" sizes="any" /></head>
      <body className={inter.className}>
       

        <main className='mx-auto'>
          {children}
        </main>
      
      </body>
    </html>
  )
}
